plugins {
	  id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.lab'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	
    implementation 'org.springframework.boot:spring-boot-starter-restclient'
    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-restclient-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'

    // AWS SDK
    implementation platform('software.amazon.awssdk:bom:2.31.54')
    implementation 'software.amazon.awssdk:sqs'

    // Spring Cloud AWS
    implementation platform('io.awspring.cloud:spring-cloud-aws-dependencies:4.1.1')
    implementation 'io.awspring.cloud:spring-cloud-aws-starter-sqs'

    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'io.github.openhtmltopdf:openhtmltopdf-pdfbox:1.1.86'
    implementation 'com.google.zxing:core:3.5.3'
    implementation 'com.google.zxing:javase:3.5.3'

    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.springframework:spring-aspects'
    implementation 'org.aspectj:aspectjrt'
}

tasks.named('test') {
	// useJUnitPlatform()
	enabled = false
}
