CREATE TABLE IF NOT EXISTS bank_slips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id TEXT NOT NULL,
    barcode TEXT,
    digitable_line TEXT,
    amount NUMERIC NOT NULL,
    due_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    paid_at TIMESTAMP,
    base64file TEXT,
    webhook_url TEXT,
    bank_code TEXT,
    beneficiary_name TEXT,
    beneficiary_document TEXT,
    agency TEXT,
    beneficiary_code TEXT,
    document_number TEXT,
    payer_name TEXT,
    payer_document TEXT,
    discount NUMERIC,
    interest NUMERIC,
    charged_amount NUMERIC,
    issue_date DATE,
    webhook_notified BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS bank_slip_failures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload TEXT,
    message_error TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    webhook_url TEXT
);